#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argcmd


class Example(argcmd.ArgCmd):
    def init(self):
        self.calls = 0

    def exit(self):
        print 'called:', self.calls

    @argcmd.argument('arg', help='arg help')
    def bar(self, args):
        print 'yey', self
        print dir(self)
        self.calls += 1
        print 'arg:', args.arg


if __name__ == '__main__':
	argcmd.main()
