#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argcmd


class Example(argcmd.ArgCmd):
    def start(self):
        self.calls = 0

    def stop(self):
        print 'called:', self.calls

    @argcmd.argument('arg', help='arg help')
    def cmd_bar(self, args):
        """function desc"""
        self.calls += 1
        print 'arg:', args.arg


if __name__ == '__main__':
	argcmd.main(shell=True)
