#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argcmd


def some_callback(parser):
    parser.add_argument('-a', '--arg', default='1', help='arg help [%(default)s]')


@argcmd.command(some_callback)
def foo(args):
    """Registered via decorator"""
    print args.arg


@argcmd.argument('arg', help='arg help')
def bar(args):
    """Registered via name"""
    print args.arg


if __name__ == '__main__':
    argcmd.main()
